MLIR_PASSES = [
    {
        "id": "string_encrypt",
        "name": "String Encryption",
        "description": "Encrypts all string literals with XOR/RC4 and decrypts at runtime",
        "default": True,
        "flag": "--string-encrypt",
    },
    {
        "id": "constant_obfuscate",
        "name": "Constant Obfuscation",
        "description": "Replaces numeric constants with opaque expressions",
        "default": True,
        "flag": "--constant-obfuscate",
    },
    {
        "id": "symbol_obfuscate",
        "name": "Symbol Obfuscation",
        "description": "Renames internal symbols to randomized identifiers",
        "default": True,
        "flag": "--symbol-obfuscate",
    },
    {
        "id": "crypto_hash",
        "name": "Cryptographic Hashing",
        "description": "Uses crypto hashing for symbol obfuscation verification",
        "default": True,
        "flag": "--crypto-hash",
    },
    {
        "id": "scf_obfuscate",
        "name": "SCF Region Obfuscation",
        "description": "Applies opaque predicates to structured control flow regions",
        "default": True,
        "flag": "--scf-obfuscate",
    },
    {
        "id": "import_obfuscate",
        "name": "Import Obfuscation",
        "description": "Hides imports behind wrapper functions",
        "default": True,
        "flag": "--import-obfuscate",
    },
]

LLVM_PASSES = [
    {
        "id": "strip_signature",
        "name": "Strip Signatures",
        "description": "Removes debug metadata and function signature information",
        "default": True,
        "flag": "strip-signature",
    },
    {
        "id": "virtualize",
        "name": "Function Virtualization",
        "description": "Converts functions to virtualized bytecode dispatchers",
        "default": True,
        "flag": "virtualize",
    },
    {
        "id": "opaque_pred",
        "name": "Opaque Predicates",
        "description": "Injects opaque predicates to obfuscate control flow",
        "default": True,
        "flag": "opaque-pred",
    },
    {
        "id": "substitution",
        "name": "Instruction Substitution",
        "description": "Replaces standard instructions with equivalent complex sequences",
        "default": True,
        "flag": "substitution",
    },
    {
        "id": "boguscf",
        "name": "Bogus Control Flow",
        "description": "Inserts opaque predicates and dead code branches",
        "default": True,
        "flag": "boguscf",
    },
    {
        "id": "flattening",
        "name": "Control Flow Flattening",
        "description": "Converts structured control flow into a switch-based dispatcher",
        "default": True,
        "flag": "flattening",
    },
    {
        "id": "linear_mba",
        "name": "Linear MBA",
        "description": "Converts arithmetic operations to mixed-boolean arithmetic",
        "default": True,
        "flag": "linear-mba",
    },
    {
        "id": "anti_debug",
        "name": "Anti-Debug Protection",
        "description": "Injects debugger detection and anti-debugging techniques",
        "default": True,
        "flag": "anti-debug",
    },
    {
        "id": "indirect_call",
        "name": "Indirect Calls",
        "description": "Converts direct calls to indirect via function pointer tables",
        "default": True,
        "flag": "indirect-call",
    },
]
