#include "forensic_types.h"
/**
 * Sigma Output Plugin
 * 
 * Generates Sigma detection rules (YAML) from IOCs and correlations.
 */

#include "forensic_types.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* ============================================================================
 * Sigma Output Implementation
 * ============================================================================ */

static int sigma_output_init(void* config) {
    (void)config;
    printf("[sigma_output] Initialized\n");
    return 0;
}

static int sigma_output_generate(const forensic_timeline_t* timeline,
                                 const forensic_ioc_list_t* iocs,
                                 const forensic_metadata_t* provenance,
                                 void* config) {
    (void)timeline;
    (void)provenance;
    
    const char* output_path = config ? (const char*)config : "forensic_rules.sigma.yaml";
    FILE* f = fopen(output_path, "w");
    if (!f) {
        fprintf(stderr, "[sigma_output] Failed to open output file: %s\n", output_path);
        return -1;
    }
    
    time_t now = time(NULL);
    struct tm* tm_info = gmtime(&now);
    char date_str[32];
    strftime(date_str, sizeof(date_str), "%Y-%m-%d", tm_info);
    
    fprintf(f, "# Sigma rules generated by JOCKY Forensic Pipeline\n");
    fprintf(f, "# Date: %s\n\n", date_str);
    
    for (size_t i = 0; i < iocs->count; i++) {
        const forensic_ioc_t* ioc = &iocs->items[i];
        
        fprintf(f, "title: JOCKY Generated Rule - %s\n", ioc->type ? ioc->type : "unknown");
        fprintf(f, "id: %ld-%zu\n", (long)now, i);
        fprintf(f, "status: experimental\n");
        fprintf(f, "description: Auto-generated from forensic analysis\n");
        fprintf(f, "author: JOCKY Forensic Pipeline\n");
        fprintf(f, "date: %s\n", date_str);
        fprintf(f, "logsource:\n");
        fprintf(f, "  product: windows\n");
        fprintf(f, "  category: process_creation\n");
        fprintf(f, "detection:\n");
        
        if (ioc->type && strcmp(ioc->type, "hash") == 0) {
            fprintf(f, "  selection:\n");
            fprintf(f, "    Hashes|contains: '%s'\n", ioc->value ? ioc->value : "");
        } else if (ioc->type && strcmp(ioc->type, "ip") == 0) {
            fprintf(f, "  selection:\n");
            fprintf(f, "    DestinationIp: '%s'\n", ioc->value ? ioc->value : "");
        } else if (ioc->type && strcmp(ioc->type, "domain") == 0) {
            fprintf(f, "  selection:\n");
            fprintf(f, "    TargetHostname|contains: '%s'\n", ioc->value ? ioc->value : "");
        } else if (ioc->type && strcmp(ioc->type, "file_path") == 0) {
            fprintf(f, "  selection:\n");
            fprintf(f, "    Image|endswith: '%s'\n", ioc->value ? ioc->value : "");
        } else {
            fprintf(f, "  selection:\n");
            fprintf(f, "    CommandLine|contains: '%s'\n", ioc->value ? ioc->value : "");
        }
        
        fprintf(f, "  condition: selection\n");
        fprintf(f, "level: medium\n");
        fprintf(f, "tags:\n");
        fprintf(f, "  - attack.execution\n");
        fprintf(f, "  - attack.t1059\n\n");
    }
    
    for (size_t i = 1; i < timeline->count; i++) {
        const forensic_event_t* prev = &timeline->items[i-1];
        const forensic_event_t* curr = &timeline->items[i];
        
        if (prev->event_type && curr->event_type &&
            strcmp(prev->event_type, "process") == 0 &&
            strcmp(curr->event_type, "process") == 0) {
            
            fprintf(f, "title: Suspicious process chain\n");
            fprintf(f, "id: %ld-chain-%zu\n", (long)now, i);
            fprintf(f, "status: experimental\n");
            fprintf(f, "description: Detected process execution chain\n");
            fprintf(f, "author: JOCKY Forensic Pipeline\n");
            fprintf(f, "date: %s\n", date_str);
            fprintf(f, "logsource:\n");
            fprintf(f, "  product: windows\n");
            fprintf(f, "  category: process_creation\n");
            fprintf(f, "detection:\n");
            fprintf(f, "  parent:\n");
            fprintf(f, "    Image|endswith: '%s'\n", prev->description ? prev->description : "");
            fprintf(f, "  child:\n");
            fprintf(f, "    Image|endswith: '%s'\n", curr->description ? curr->description : "");
            fprintf(f, "  condition: parent and child\n");
            fprintf(f, "level: high\n");
            fprintf(f, "tags:\n");
            fprintf(f, "  - attack.execution\n");
            fprintf(f, "  - attack.t1059.001\n\n");
        }
    }
    
    fclose(f);
    printf("[sigma_output] Sigma rules written to %s\n", output_path);
    return 0;
}

static void sigma_output_cleanup(void) {
    printf("[sigma_output] Cleanup\n");
}

/* ============================================================================
 * Plugin Definition
 * ============================================================================ */

static const char* sigma_capabilities[] = {
    "write_report"
};

forensic_output_plugin_t sigma_output_plugin = {
    .name = "sigma_output",
    .version = "1.0.0",
    .description = "Generates Sigma detection rules from IOCs and correlations",
    .init = sigma_output_init,
    .generate = sigma_output_generate,
    .cleanup = sigma_output_cleanup,
    .required_capabilities = sigma_capabilities,
    .capability_count = sizeof(sigma_capabilities) / sizeof(sigma_capabilities[0])
};